### ISSUE TITLE
About parameterized builds in Jenkins job limit

### ISSUE THREAD

**Issue by espala** [ParameterizedBuilds/parameterized-builds#224]
Hi,

I'm using "parametrized build for jenkins" on bitbucket server. There are 67 definitions that I have defined before. But when I want to add a new one, it gives an error.

I'm deleting the 67th record and it doesn't give an error when I add it again. But it makes an error when he tries to add a 68th record.

Is there a limit?

I don't know how to solve it. Can you help me ?

Atlassian Bitbucket v6.0.1
Plugin Installed :4.0.2

bitbucket generic log;
error: An error occurred while processing the request. Check the server logs for more information.

bitbucket txt log;
2019-09-30 13:04:07,682 ERROR [https-jsse-nio-8443-exec-217] admin.user @FSWYL5x784x118424x0 1y8r9yz 213.74.20.110:50407,0:0:0:0:0:0:0:1 "PUT /rest/api/latest/projects/TOW/repos/services/settings/hooks/com.kylenicholls.stash.parameterized-builds:parameterized-build-hook/enabled HTTP/1.1" c.a.s.i.r.e.DefaultUnhandledExceptionMapperHelper Unhandled exception while processing REST request: "PUT /rest/api/latest/projects/TOW/repos/microservices/settings/hooks/com.kylenicholls.stash.parameterized-builds:parameterized-build-hook/enabled HTTP/1.1"
java.lang.IllegalArgumentException: The provided LOB data is too long
at com.google.common.base.Preconditions.checkArgument(Preconditions.java:141)
at com.atlassian.stash.internal.setting.InternalSharedLob$Builder.data(InternalSharedLob.java:86)
at com.atlassian.stash.internal.repository.InternalRepositoryHook$Builder.settings(InternalRepositoryHook.java:226)
at com.atlassian.stash.internal.hook.repository.DefaultRepositoryHookService.updateHook(DefaultRepositoryHookService.java:839)
at com.atlassian.stash.internal.hook.repository.DefaultRepositoryHookService.setEnabled(DefaultRepositoryHookService.java:807)
at com.atlassian.stash.internal.hook.repository.DefaultRepositoryHookService.enable(DefaultRepositoryHookService.java:206)
at com.atlassian.plugin.util.ContextClassLoaderSettingInvocationHandler.invoke(ContextClassLoaderSettingInvocationHandler.java:26)
at org.eclipse.gemini.blueprint.service.importer.support.internal.aop.ServiceInvoker.doInvoke(ServiceInvoker.java:56)
at org.eclipse.gemini.blueprint.service.importer.support.internal.aop.ServiceInvoker.invoke(ServiceInvoker.java:60)
at org.eclipse.gemini.blueprint.service.util.internal.aop.ServiceTCCLInterceptor.invokeUnprivileged(ServiceTCCLInterceptor.java:70)
at org.eclipse.gemini.blueprint.service.util.internal.aop.ServiceTCCLInterceptor.invoke(ServiceTCCLInterceptor.java:53)
at org.eclipse.gemini.blueprint.service.importer.support.LocalBundleContextAdvice.invoke(LocalBundleContextAdvice.java:57)
at com.atlassian.stash.internal.rest.hook.RepositoryHookResourceHelper.enableHook(RepositoryHookResourceHelper.java:71)
at com.atlassian.stash.internal.rest.hook.RepositoryHookRepositoryResource.enableHook(RepositoryHookRepositoryResource.java:108)
at com.atlassian.applinks.core.rest.context.ContextFilter.doFilter(ContextFilter.java:24)
at com.atlassian.applinks.core.rest.context.ContextFilter.doFilter(ContextFilter.java:24)
at com.atlassian.applinks.core.rest.context.ContextFilter.doFilter(ContextFilter.java:24)
at com.atlassian.applinks.core.rest.context.ContextFilter.doFilter(ContextFilter.java:24)
at com.atlassian.applinks.core.rest.context.ContextFilter.doFilter(ContextFilter.java:24)
at com.atlassian.analytics.client.filter.UniversalAnalyticsFilter.doFilter(UniversalAnalyticsFilter.java:92)
at com.atlassian.analytics.client.filter.AbstractHttpFilter.doFilter(AbstractHttpFilter.java:39)
at com.atlassian.bitbucket.internal.xcode.web.XcodeUserAgentFilter.doFilter(XcodeUserAgentFilter.java:36)
at com.atlassian.stash.internal.spring.lifecycle.LifecycleJohnsonServletFilterModuleContainerFilter.doFilter(LifecycleJohnsonServletFilterModuleContainerFilter.java:42)
at com.atlassian.plugin.connect.plugin.auth.scope.ApiScopingFilter.doFilter(ApiScopingFilter.java:81)
at com.atlassian.stash.internal.spring.lifecycle.LifecycleJohnsonServletFilterModuleContainerFilter.doFilter(LifecycleJohnsonServletFilterModuleContainerFilter.java:42)
at com.atlassian.stash.internal.spring.security.StashAuthenticationFilter.doFi

**Comment by a-hacker** [comment]
Hi @espala. The job definitions are stored in the bitbucket server database. All job definitions for a given repo will be stored together in one row of the repo hook settings table (STA_REPO_HOOK or something like that). The size constraint is placed there by Bitbucket, not us. This does mean that there is a size limit to the data but not a definitive limit to the number of jobs since the size of a given job can fluctuate.

Unless we significantly change the way we store job data, there's nothing we can do in the plugin to fix this. There might be a way to configure the size limit for that column in the database. Other than that, I'd recommend consolidating your triggers into a few jobs that can call whatever subjobs you need to run.

I'm going to leave this issue open as a documentation ticket.

**Comment by espala** [comment]
Hi @a-hacker. 

first of thank you for your interest and support.

I can't combine jobs.. job architecture is not suitable for this. 
I'm trying to create a new job as empty. But again, it gives the same error.

I'm getting this error before the request falls to sql yet. could it be related to Bitbucket's limits on sending to SQL ? Or could this plugin be an unnoticed bug ?

I'm waiting for plugin developer to deal with this problem. Nobody seems to have gotten a mistake like this before.  So no one's been using it more intensively than me. So I think it is.

If I can't solve this problem, I'll have to redesign all my ci/cd processes. So what do I do now?

**Comment by a-hacker** [comment]
I'm not suggesting you combine jobs, just create some sort of entrypoint jobs. For instance, if you have jobA and jobB that both trigger on PR merges, create a PrMergedJob that calls jobA and jobB without blocking on either. Any parameters you need can be added to the entrypoint job and passed into the subjobs. 

If you can't do this, then you will likely need to redesign your processes. Since this is a limitation of Bitbucket Server there is really nothing that can be done to the plugin to fix this.

**Comment by bturner** [comment]
I'm the principal developer for Bitbucket Server, and this was forwarded to me by our support team.

> Since this is a limitation of Bitbucket Server there is really nothing that can be done to the plugin to fix this.

That's not really true, but I can understand why it feels that way. The hook settings support Bitbucket Server offers is intended for _lightweight, simple_ configuration. For apps that require more complex configuration, the expectation is that the app will provide its own persistence approach, which will likely be built on ActiveObjects (but could potentially also be built on `PluginSettings` instead, though I wouldn't recommend it).

_Please note_: I'm simply sharing the expectation, which was likely never documented, with which this functionality was built. I'm not casting judgment on anyone's work--especially given the lack of discoverability for said expectation.

The implementation for our hook configuration has its limit applied by an annotation, which means the limit must be a compile-time constant. This being programming, I won't pretend or imply it is _impossible_ to make it configurable, but I will say it is enough work that it's unlikely to happen. This functionality was added in Stash 2.2, which shipped in January 2013. In the nearly 9 years since, this is the first time I've ever seen a report of an app running into the 32K limit. When it comes to prioritizing a change that is potentially complex or risky, that doesn't give it very good odds.

I'd be happy to offer guidance or review if you want to try and set up your own persistence, including how you could bridge between the old and new such that existing installs can upgrade without losing their settings.

**Comment by a-hacker** [comment]
Thanks for the info @bturner! I appreciate the offer of guidance but I haven't been actively developing this plugin for awhile and am now in the process of deprecating it so it shouldn't be necessary.

I also apologize if I made it sound like I was blaming you/Atlassian for this issue. My initial response was meant to indicate that with the current implementation of the settings, the issue can not be easily resolved. Only through an overhaul of the persistence, as you mentioned, could this limitation be avoided. Given that this is an unusual case of an exceedingly high job count, it's really not worth doing anyways.
