### ISSUE TITLE
Jenkins jobs not triggered anymore after Bitbucket upgrade from 6.7.2 to 6.10.0

### ISSUE THREAD

**Issue by Lahres-Dev** [ParameterizedBuilds/parameterized-builds#255]
Version information:

- Parameterized Builds for Jenkins 4.0.9
- Atlassian Bitbucket v6.10.0
- Jenkins ver. 2.182

Bitbucket log:
```
2020-01-15 10:29:33,428 ERROR [threadpool:thread-4]  c.a.s.i.c.DefaultTransferableStateManager Error while processing asynchronous task 
java.lang.NullPointerException: null 
        at java.lang.StringBuilder.<init>(StringBuilder.java:112) 
        at com.kylenicholls.stash.parameterizedbuilds.item.Job.setUrlPath(Job.java:318) 
        at com.kylenicholls.stash.parameterizedbuilds.item.Job.buildUrl(Job.java:254) 
        at com.kylenicholls.stash.parameterizedbuilds.ciserver.Jenkins.triggerJob(Jenkins.java:300) 
        at com.kylenicholls.stash.parameterizedbuilds.eventHandlers.BaseHandler.triggerJenkins(BaseHandler.java:41) 
        at com.kylenicholls.stash.parameterizedbuilds.eventHandlers.BaseHandler.run(BaseHandler.java:35) 
        at com.kylenicholls.stash.parameterizedbuilds.eventHandlers.PRHandler.run(PRHandler.java:53) 
        at com.kylenicholls.stash.parameterizedbuilds.PullRequestHook.lambda$0(PullRequestHook.java:110) 
        at com.atlassian.stash.internal.concurrent.DefaultTransferableStateManager$StateTransferringRunnable.run(DefaultTransferableStateManager.java:166) 
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) 
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) 
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180) 
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293) 
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) 
        at java.lang.Thread.run(Thread.java:748) 
        ... 1 frame trimmed
```

More information can be provided if necessary.

**Comment by a-hacker** [comment]
Hey @Lahres-Dev, it looks like the null value is coming from the jenkins url. Can you double check that you have your server settings configured correctly and a valid jenkins server chosen in the job settings?

**Comment by a-hacker** [comment]
Interesting. Thank you for the detailed report! I'll update my test settings to run against 6.10.0 to see if its a version issue with Bitbucket. I probably won't get around to it until later today though. Will let you know if I'm able to reproduce.

**Comment by a-hacker** [comment]
Looks like it's not an issue with the Bitbucket version. Do you know what version of the plugin you were on before the upgrade?

**Comment by Lahres-Dev** [comment]
We used version 4.0.9

![image](https://user-images.githubusercontent.com/58905132/72708297-b784f800-3b62-11ea-9600-7fa8ad80c0b4.png)

**Comment by a-hacker** [comment]
Got it. That's very odd that a minor Bitbucket upgrade would cause as issue like this. The fact that I can't replicate the issue is even stranger.

I don't think this is a data corruption issue because then that would affect the project or repository settings pages as well.

I've created a test jar with a small change that might fix this issue. Since I can't reproduce it's a shot in the dark but I'd appreciate if you could install it and give it a quick test. The jar is located [here](https://github.com/ParameterizedBuilds/parameterized-builds/releases/tag/untagged-3fc28cecd7c342b4e56f).

**Comment by fzikowsky** [comment]
I would try the jar but the link is broken(404) ?

we have a very similar problem with the same error(without trace)

**Comment by Lahres-Dev** [comment]
> Got it. That's very odd that a minor Bitbucket upgrade would cause as issue like this. The fact that I can't replicate the issue is even stranger.
> 
> I don't think this is a data corruption issue because then that would affect the project or repository settings pages as well.
> 
> I've created a test jar with a small change that might fix this issue. Since I can't reproduce it's a shot in the dark but I'd appreciate if you could install it and give it a quick test. The jar is located [here](https://github.com/ParameterizedBuilds/parameterized-builds/releases/tag/untagged-3fc28cecd7c342b4e56f).

I'll gladly help. Let me know when the link works (currently a 404 like @fzikowsky says)

**Comment by a-hacker** [comment]
Sorry about that. I didn't realize that a draft release was private. [Here's a proper link](https://github.com/ParameterizedBuilds/parameterized-builds/releases/tag/4.0.11b) (jar is under assets).

**Comment by fzikowsky** [comment]
with the new jar
> 2020-01-22 20:35:25,342 ERROR [http-nio-7990-exec-6] fzikowsky @AZC1NJx1235x111x0 2wn6px 79.216.192.81,10.240.19.10 "POST /rest/parameterized-builds/latest/projects/XXXX/repos/XXXX/triggerBuild/0/dev HTTP/1.1" c.a.p.r.c.e.j.ThrowableExceptionMapper Uncaught exception thrown by REST service: null
java.lang.NullPointerException: null
        at java.lang.StringBuilder.<init>(StringBuilder.java:112)
        at com.kylenicholls.stash.parameterizedbuilds.item.Job.setUrlPath(Job.java:318)
        at com.kylenicholls.stash.parameterizedbuilds.item.Job.buildUrl(Job.java:254)
        at com.kylenicholls.stash.parameterizedbuilds.ciserver.Jenkins.triggerJob(Jenkins.java:302)
        at com.kylenicholls.stash.parameterizedbuilds.rest.BuildResource.triggerBuild(BuildResource.java:109)
        at com.atlassian.applinks.core.rest.context.ContextFilter.doFilter(ContextFilter.java:24)
        at com.atlassian.applinks.core.rest.context.ContextFilter.doFilter(ContextFilter.java:24)

maybe its a different problem?

**Comment by syryin** [comment]
Hi,
Same issue here. We are trying v4.0.10 plugin in v6.10 BitBucket (Data Center). The Jenkins trigger is not successful.

**Comment by Lahres-Dev** [comment]
Doesn't work here either.

**Comment by a-hacker** [comment]
I was finally able to reproduce and I believe I have delivered a fix in release 4.0.11. Could one of you upgrade and confirm if the new version fixes the issue?

**Comment by Lahres-Dev** [comment]
Hey @a-hacker, it seems to be working again. I'll keep an eye on it today. :)

![image](https://user-images.githubusercontent.com/58905132/73154036-47342480-40d6-11ea-8b77-dd4fa39cf6bd.png)

Thank you for your effort.

**Comment by syryin** [comment]
Thanks @a-hacker, v4.0.11 works great
