### ISSUE TITLE
Can't configure Parameterized Builds for Jenkins in users repositories

### ISSUE THREAD

**Issue by bstantz-harris** [ParameterizedBuilds/parameterized-builds#257]
### Bug

- _Parameterized Builds for Jenkins_ plugin version - 4.0.10
- _Bitbucket_ version - 6.9.1
- _Jenkins_ Version - 2.73.3

Since upgrading to BitBucket 6.9.1 users are unable to enable or edit previously configurations of the plugin.  The error 'Unable to render configuration form for Parameterized Builds for Jenkins' is displayed when enabling or editing the current configuration.

The app works as expected in any repository other than personal repos.

I don't see an error reported in the atlassian-bitbucket.log when either action is performed.

I do see a smattering of the following error in the log, however it isn't generated when enabling or editing the app in the users repository.

2020-01-21 07:46:37,401 ERROR [threadpool:thread-2]  c.a.s.i.c.DefaultTransferableStateManager Error while processing asynchronous task
java.lang.NullPointerException: null
    at com.kylenicholls.stash.parameterizedbuilds.ciserver.Jenkins.triggerJob(Jenkins.java:307)
    at com.kylenicholls.stash.parameterizedbuilds.eventHandlers.BaseHandler.triggerJenkins(BaseHandler.java:41)
    at com.kylenicholls.stash.parameterizedbuilds.eventHandlers.BaseHandler.run(BaseHandler.java:35)
    at com.kylenicholls.stash.parameterizedbuilds.ParameterizedBuildHook.lambda$0(ParameterizedBuildHook.java:69)
    at com.atlassian.stash.internal.concurrent.DefaultTransferableStateManager$StateTransferringRunnable.run(DefaultTransferableStateManager.java:166)
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
    at java.util.concurrent.FutureTask.run(FutureTask.java:266)
    at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
    at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
    at java.lang.Thread.run(Thread.java:748)
    ... 1 frame trimmed

**Comment by a-hacker** [comment]
Hi @bstantz-harris. Where you previously on a Bitbucket Server 6.X version prior to the upgrade? If so, you may want to revert the Parameterized Builds for Jenkins plugin back to whatever version you were on before.

User repos haven't really been officially supported so I'm surprised they were ever working to begin with. Adding back in support for user repos may be difficult as there are a lot of places in code that assume a valid project key.

**Comment by bstantz-harris** [comment]
Hello, and thank you for the quick response.

I actually had to upgrade from BitBucket 4.14.11.  In order to accomplish the upgrade I upgraded to BitBucket 5.16.0 then 6.9.1.

I'm not sure what version of Parameterized Builds I used in BitBucket 4.14, the logs show I installed  3.2.10 then 4.0.9 and finally 4.0.10.

fwiw, I have a 5.11.1 BitBucket instance with Parameterized Builds version 3.2.10; the addon works for users repositories in that combination.

**Comment by a-hacker** [comment]
Thanks for the info. I'll try to see if there is an easy way to get user repos supported again but if not, it may take awhile for that feature to be re-added.

If you need help removing hook settings for some of those repos, I can help provide details on where in the Bitbucket db those settings are saved.

**Comment by bstantz-harris** [comment]
Thanks again, I think I am good with leaving the DB entries for now.  It looks like we will need to move the repos out to a 'valid project'; at least for now.
