### ISSUE TITLE
Error message from the plugin when opening PR overview screen in Bitbucket on projects that have not enabled the plugin.

### ISSUE THREAD

**Issue by s1rlon** [ParameterizedBuilds/parameterized-builds#281]
When opening a PR overview screen (projects/PRJ/repos/bwoken/pull-requests/1/overview) for any project in Bitbucket 7.0.1, if plugin has not been enabled for that project throws ERROR popup and following in the logs:

`
2020-03-23 07:25:02,390 ERROR [http-nio-7990-exec-6] * "GET /rest/parameterized-builds/latest/projects/***/repos/***/getJobs HTTP/1.1" c.k.s.p.helper.SettingsService Exception in SettingsService.getSettings: null
java.lang.NullPointerException: null
        at com.kylenicholls.stash.parameterizedbuilds.helper.SettingsService$1.perform(SettingsService.java:59)
        at com.kylenicholls.stash.parameterizedbuilds.helper.SettingsService$1.perform(SettingsService.java:52)
        at com.atlassian.stash.internal.user.DefaultEscalatedSecurityContext.call(DefaultEscalatedSecurityContext.java:59)
        at com.kylenicholls.stash.parameterizedbuilds.helper.SettingsService.getSettings(SettingsService.java:52)
        at com.kylenicholls.stash.parameterizedbuilds.rest.BuildResource.getJobs(BuildResource.java:151)
        at com.atlassian.applinks.core.rest.context.ContextFilter.doFilter(ContextFilter.java:24)
        at com.atlassian.applinks.core.rest.context.ContextFilter.doFilter(ContextFilter.java:24)
        at com.atlassian.applinks.core.rest.context.ContextFilter.doFilter(ContextFilter.java:24)
        at com.atlassian.applinks.core.rest.context.ContextFilter.doFilter(ContextFilter.java:24)
        at com.atlassian.applinks.core.rest.context.ContextFilter.doFilter(ContextFilter.java:24)
        at com.atlassian.bitbucket.internal.xcode.web.XcodeUserAgentFilter.doFilter(XcodeUserAgentFilter.java:36)
        at com.atlassian.analytics.client.filter.UniversalAnalyticsFilter.doFilter(UniversalAnalyticsFilter.java:75)
        at com.atlassian.analytics.client.filter.AbstractHttpFilter.doFilter(AbstractHttpFilter.java:33)
        at com.atlassian.stash.internal.spring.lifecycle.LifecycleJohnsonServletFilterModuleContainerFilter.doFilter(LifecycleJohnsonServletFilterModuleContainerFilter.java:42)
        at com.atlassian.bitbucket.internal.ratelimit.servlet.filter.RateLimitFilter.doFilter(RateLimitFilter.java:75)
        at com.atlassian.plugin.connect.plugin.auth.scope.ApiScopingFilter.doFilter(ApiScopingFilter.java:81)
        at com.atlassian.stash.internal.spring.lifecycle.LifecycleJohnsonServletFilterModuleContainerFilter.doFilter(LifecycleJohnsonServletFilterModuleContainerFilter.java:42)
        at com.atlassian.stash.internal.spring.security.StashAuthenticationFilter.doFilter(StashAuthenticationFilter.java:85)
        at com.atlassian.stash.internal.web.auth.BeforeLoginPluginAuthenticationFilter.doInsideSpringSecurityChain(BeforeLoginPluginAuthenticationFilter.java:112)
        at com.atlassian.stash.internal.web.auth.BeforeLoginPluginAuthenticationFilter.doFilter(BeforeLoginPluginAuthenticationFilter.java:75)
        at com.atlassian.security.auth.trustedapps.filter.TrustedApplicationsFilter.doFilter(TrustedApplicationsFilter.java:94)
        at com.atlassian.oauth.serviceprovider.internal.servlet.OAuthFilter.doFilter(OAuthFilter.java:67)
        at com.atlassian.stash.internal.spring.lifecycle.LifecycleJohnsonServletFilterModuleContainerFilter.doFilter(LifecycleJohnsonServletFilterModuleContainerFilter.java:42)
        at com.atlassian.plugin.connect.plugin.auth.oauth2.DefaultSalAuthenticationFilter.doFilter(DefaultSalAuthenticationFilter.java:69)
        at com.atlassian.plugin.connect.plugin.auth.user.ThreeLeggedAuthFilter.doFilter(ThreeLeggedAuthFilter.java:109)
        at com.atlassian.jwt.internal.servlet.JwtAuthFilter.doFilter(JwtAuthFilter.java:37)
        at com.atlassian.analytics.client.filter.DefaultAnalyticsFilter.doFilter(DefaultAnalyticsFilter.java:33)
        at com.atlassian.analytics.client.filter.AbstractHttpFilter.doFilter(AbstractHttpFilter.java:33)
        at com.atlassian.stash.internal.spring.lifecycle.LifecycleJohnsonServletFilterModuleContainerFilter.doFilter(LifecycleJohnsonServletFilterModuleContainerFilter.java:42)
        at com.atlassian.stash.internal.web.auth.BeforeLoginPluginAuthenticationFilter.doBeforeBeforeLoginFilters(BeforeLoginPluginAuthenticationFilter.java:90)
        at com.atlassian.stash.internal.web.auth.BeforeLoginPluginAuthenticationFilter.doFilter(BeforeLoginPluginAuthenticationFilter.java:73)
        at com.atlassian.stash.internal.request.DefaultRequestManager.doAsRequest(DefaultRequestManager.java:87)
        at com.atlassian.stash.internal.hazelcast.ConfigurableWebFilter.doFilter(ConfigurableWebFilter.java:38)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.lang.Thread.run(Thread.java:748)
        ... 249 frames trimmed
`

![image](https://user-images.githubusercontent.com/9053187/77292711-80a99a80-6ce9-11ea-9bbc-95c26aff7246.png)

In the access logs ther's a 404 for the getJobs request, as it's never generated I assume.

**Comment by s1rlon** [comment]
Downgrading to 4.0.13 gets rid of the error message

**Comment by s1rlon** [comment]
This only happens for repositories that have the plugin disabled. If I enable the plugin on the repository and just set up a dummy job, the error is no longer there.
So it seems that the plugin is trying to load information on the PR overview screen, even if it has not been enabled for that repository.

**Comment by CarpeCervisiam** [comment]
We've been having this issue since Friday. We have over a hundred repos so the above workaround isn't really practical. Downgrading to 4.0.13, automated builds do not seem to work. So as of now we have to choose between, an error message on all pull requests and no automated builds being triggered.

**Comment by s1rlon** [comment]
The plugin also creates the "Build in Jenkins" menu option for all repositories that have ever enabled the plugin.

The check to see if the plugin is actually enabled seems to be missing for the PR overview screen.

**Comment by a-hacker** [comment]
Thank you for the issue @s1rlon. I have a fix in #287. However, when I disable the hook, I no longer see the "Build in Jenkins" button. Did you update the page after disabling the plugin?

**Comment by s1rlon** [comment]
I don't see it anymore either, maybe something was cached.

**Comment by a-hacker** [comment]
Fixed in 5.0.1
